spring:
    application:
        name: discovery
server:
    port: 21001

eureka:
    instance:
        hostname: localhost

    client:
        serviceUrl:
            defaultZone: http://localhost:21001/eureka/
        register-with-eureka: false
        fetch-registry: false