spring:
	application:
		name: discovery
server:
	port: 8085
 
eureka:
 	instance:
  		hostname: localhost
 
	client:
		serviceUrl:
			defaultZone: http://localhost:8085/eureka/
		register-with-eureka: false
		fetch-registry: false