spring:
    application:
        name: discovery
server:
    port: 9001

eureka:
    instance:
        hostname: discoveryservice

    client:
        serviceUrl:
            defaultZone: http://discoveryservice:9001/eureka/
        register-with-eureka: false
        fetch-registry: false