spring:
    application:
        name: discovery
server:
    port: 8000

eureka:
    instance:
        hostname: discovery-service

    client:
        serviceUrl:
            defaultZone: http://discovery-service:8000/eureka/
        register-with-eureka: false
        fetch-registry: false
