spring:
    application:
        name: gateway
server:
    port: 21010

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 10

zuul:
    routes: 
        discovery:
            path: /discovery/**
            sensitive-headers: Set-Cookie,Authorization
            url: http://localhost:21001
        resort-service:
            path: /resort-service/**
            sensitive-headers: Set-Cookie,Authorization