server:
  host: ${HOSTNAME:localhost}
  port: ${PORT:9090}

spring:
    application:
        name: gateway

#zuul:
#    routes: 
#        discovery:
#            path: /discovery/**
#            sensitive-headers: Set-Cookie,Authorization
#            url: http://discoveryservice:9001
#        resort:
#            path: /resort-service/**
#            sensitive-headers: Set-Cookie,Authorization
#        webapp:
#            path: /web/**
#            sensitive-headers: Set-Cookie,Authorization
