server:
  port: ${RESORT_PORT:11003}

database:
#  dbhost: 
  dbhost: $(DB_HOST}
  dbport: 1521
  dbservicename: $(DB_SERVICE}
  dbuser: $(DB_USER}
  dbpassword: $(DB_PASSWD}
  dbdriver: oracle.jdbc.OracleDriver

#database:
#  dbhost: postgres
#  dbport: 5432
#  dbuser: testuser
#  dbpassword: testuser
#  dbname: testdb


spring:
  application:
    name: resort
  datasource:
    url: jdbc:oracle:thin:@${database.dbhost}:${database.dbport}/${database.dbservicename}
    username: ${database.dbuser}
    password: ${database.dbpassword}
    driver-class-name: ${database.dbdriver}
    hikari:
      minimumIdle: 2
#  datasource:
#    url: jdbc:postgresql://${database.dbhost}:${database.dbport}/${database.dbname}
#    username: ${database.dbuser}
#    password: ${database.dbpassword}
#    hikari:
#      minimumIdle: 2
