spring:
    application:
        name: resort-service
    datasource:
        url: jdbc:postgresql://postgres:5432/testdb
        username: testuser
        password: testuser
        hikari:
            minimumIdle: 2

server:
    port: 9002

eureka:
  client:
    enabled: true
    defaultZone: http://discoveryservice:9001/eureka/
    region: default
    registryFetchIntervalSeconds: 10
