spring:
    application:
        name: resort-service
    datasource:
        url: jdbc:postgresql://localhost:5432/testdb
        username: testuser
        password: testuser

server:
    port: 8901

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 10
