spring:
    application:
        name: resort-service
    datasource:
        url: jdbc:postgresql://localhost:5432/testdb
        username: testuser
        password: testuser
        hikari:
            minimumIdle: 2

server:
    port: 21002

eureka:
  client:
    enabled: true
    region: default
    registryFetchIntervalSeconds: 10
