server:
  host: ${WEBAPP_HOST:localhost}
  port: ${WEBAPP_PORT:11004}

spring:
  application:
    name: webapp
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
