server:
  host: ${HOSTNAME:localhost}
  port: ${PORT:11000}

spring:
  application:
    name: webapp
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
